# Generated by Django 5.2.9 on 2025-12-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_booking_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('main', 'Основні страви'), ('salad', 'Cалати'), ('soup', 'Супи'), ('dessert', 'Десерти'), ('drink', 'Hanoї')], default='main', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
